//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNET_MVC_Samples
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChamberDtl
    {
        public int ChamberId { get; set; }
        public string ChamberName { get; set; }
        public bool Status { get; set; }
        public string Description { get; set; }
        public string Remarks { get; set; }
    }
}
