//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNET_MVC_Samples
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TempHumidityEntities1 : DbContext
    {
        public TempHumidityEntities1()
            : base("name=TempHumidityEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChamberDtl> ChamberDtls { get; set; }
        public virtual DbSet<Temp> Temps { get; set; }
        public virtual DbSet<Humidity> Humidities { get; set; }
    }
}
